# This file describes the network interfaces available on your system
# For more information, see netplan(5).
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      addresses: [192.168.100.102/24]
      dhcp4: no
    enp0s8:
      dhcp4: yes
